$ANSIBLE_VAULT;1.1;AES256
66353130303138626430363732623039376464373566383037663665376565353033393265303137
6364386639383466633533666635373331616665626566370a396131323264653338656334626361
36366137313361653961393637366331643463353937616161316363646332373937633562623831
3864316163373930650a313535313765313638663734313337316437663537666130393330383835
30306466303138656565373738636662643165663363356138333532356539613630316565363031
32376234343136633534343164383030666631343331653236633331613539666131623139343763
32383439373335393235626534353565646333663636323561356439363834306561396231333235
35656433313930366431643830613437353736356465653736613362303761336337383466646364
3936
